#!/usr/bin/env bash

set -e

BASH_TOOLBOX="$(dirname "$0")"

# Make sure everything is logged.
LOG_TRACE=1 LOG_DEBUG=1 LOG_INFO=1 LOG_WARN=1
LOG_DRY_RUN=1

source "${BASH_TOOLBOX:?}"/colors.sh
printf "${Bold}# Coloring${Bold_Off}\n\n"

printf "You can do ${Bold}bold${Bold_Off}, ${Underline}underline${Underline_Off} or ${Dark}dim${Dark_Off} text.\n"
printf "You can also do ${Yellow}yellow${Color_Off} or ${Red}a${Green}n${Blue}y${Color_Off} ${Purple}co${Cyan}lor${Color_Off} text.\n"

source "${BASH_TOOLBOX:?}"/format.sh
printf "\n${Bold}# Formatting${Bold_Off}\n\n"

printf "Here is how are formatted $(format_url 'URLs'), $(format_code 'code'), $(format_command 'commands'), $(format_flag 'flags'), $(format_arg 'args'), $(format_opt_arg 'optional args'), $(format_title 'titles'), $(format_subtitle 'subtitles') and $(format_secondary 'secondary text').\n"
printf "You can also print $(format_hyperlink 'hyperlinks' 'https://github.com/RemiBardon/bash-toolbox')!\n"

printf "\n${Bold}# Decoloring${Bold_Off}\n\n"
printf "Some $(format_code "decolored inline code" | decolor) and some $(format_url "decolored URL" | decolor).\n"

source "${BASH_TOOLBOX:?}"/log.sh
printf "\n${Bold}# Logging${Bold_Off}\n\n"

trace "A $(format_code trace) log"
debug "A $(format_code debug) log"
info "A $(format_code info) log"
warn "A $(format_code warn) log"
error "A $(format_code error) log"
success "A $(format_code success) log"
question "A $(format_code question) log"

printf "\n${Bold}# Logging + style${Bold_Off}\n\n"

error "Some $(format_code 'formatted text') in an error"
warn "An $(format_url 'URL') in a warning"
trace "Some ${Bold}bold text${Bold_Off} in a trace"
info "$(cat <<EOF
It also works
with multiline text
EOF
)"

source "${BASH_TOOLBOX:?}"/edo.sh
printf "\n${Bold}# Execute + log${Bold_Off}\n\n"

printf "$(format_code 'log_as_info_ cat '"'$0'"' | head -n 3'):\n"
log_as_info_ cat "$0" 2>&1 | head -n 3

printf '\nExit codes are propagated:\n'

( set +e; edo log_as_trace_ cp foo bar; info "Exit code: $?" )
